Add stricter type-protection for the handler (#6)
:recycle: Add stricter type-protection for the handler.

Since the handler is meant to be a function, add more precise protection for it.

Right now, passing any non-function value would result in a noop.

```js
useBeforeunload(null); // noop
useBeforeunload([]);   // noop
useBeforeunload({});   // noop
// ...
```

This diverges slightly from the current behavior which would  (albeit accidentally) cause an exception when a `handler` is provided that is truthy but not a function:

```js
useBeforeunload([]);   // Uncaught TypeError: handerRef.current is not a function
useBeforeunload({});   // Uncaught TypeError: handerRef.current is not a function
// ...
```

If an error-throwing fail-first approach is more suitable than a noop (which IMHO it is), something like this would be more appropriate:

```js
// ...
if (!['undefined', 'function'].includes(typeof handlerRef.current)) {
  throw new Error(`Passed in handler must be a function but you passed in a/an ${typeof handlerRef.current}`);
}

if (typeof handlerRef === 'function') {
  returnValue = handlerRef.current(event);  
}
// ...
```